default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: unter_platform_development

test:
  <<: *default
  database: unter_platform_test

production:
  <<: *default
  database: unter_platform_production
  username: unter_platform
  password: <%= ENV['UNTER_PLATFORM_DATABASE_PASSWORD'] %>
